### ISSUE TITLE
PM Review #1: Design Documents/Wiki

### ISSUE THREAD

**Issue by andrewlangston** [bhanu-gupta/funbook#1]
Hi Bhanu,

Great job with your design documents. Some preliminary comments on what you've been assigned thus far (MVP list, schema, sample state):

**MVP LIST**
- [x] This looks good - but there is a stray entry under `5. Comments/posting on each others' walls`: "Logged in users can edit the body"

**SCHEMA**
- [x] On the `users` table, you can remove` mobile_number, `profile_pic_id`, and `cover_pic_id`. We won't ask that you implement any kind of mobile integration, and any images hosted by users will be accomplished through Amazon Web Services and ActiveStorage (more on this next week). They won't be directly referenced in your schema design.
- [x] Similarly, you can remove `img_url` from the `photos` table (these can also be handled as above).
- [x] What is the purpose of the `removed` column in `photos` and `albums`? Would we not just delete database records when we want to 'remove' them?

**SAMPLE STATE**
- [x] Keys in our state should be `camelCase` rather than `snake_case`, as is JavaScript convention.
- [x] Given comments to your schema, I don't think we need `phone`, `profile_pic_id`, or `cover_pic_id` in your `users` slice of state. We also shouldn't need to hold `friend_post_ids` (we can use a selector to find these). We can also combine `received_friend_ids` and `sent_friend_ids` into `pendingFriendIds`, or something to that effect.
- [x] In your `posts` slice of state, why are we nesting objects under the `comment_ids` key?

Let me know if you have any questions!

**Comment by bhanu-gupta** [comment]
Thanks for your feedback Andrew. 

**Images**
I am not able to understand how the image upload process works with Amazon web services. But, I was thinking maybe we have to save the image url in the database otherwise how will we fetch the profile image and cover image of a particular user? Also, does it mean I don't need the photos table at all?

**friend_post_ids** are the ids post ids of friends who have posted on the wall of a particular user. I thought it would be difficult to get the post ids through selector as then we would have to iterate over all the posts and get the posts where author_id = all friends of the user and user_id is the current user.

**received_friend_ids and sent_friend_ids** I kept them separate so that I know which are the pending friend requests for the current user and also the sent_friend_ids which are the friend requests sent by the current user but which are still pending so that I can show the status as pending on the friends profile page.

**comment_ids** I nested them so that I know all nested comment ids for a post like comments on comments. Is there a better way to get this information?

**Comment by andrewlangston** [comment]
Bhanu - thanks for the quick response. To your comments:

+ We will talk through AWS integration next week. For now, just know that we will not have to hold an image URL for any resources in our database. These will instead be facilitated by an association using ActiveStorage (see the Rails docs for details).
+ Ultimately, you probably won't need to fetch *all* posts from your database. In fact, your `api/posts#index` action should only fetch posts relevant to the current user, obviating the need to keep an independent reference those post IDs in your frontend state. Further iterating over this subset of posts via selector should not be a problem.
+ You're absolutely right about separating received and sent friend requests. Keep as is!
+ Since each `comment` in your sample state holds reference to its subcomments, a `post` only needs to hold an array of ids pointing to its top-level `comments`. You can change this key in your state to an array accordingly.

Some additional comments regarding your route design documents:

**BACKEND ROUTES**
- [ ] You will need a way to fetch users in bulk (for example, to fetch information on a single user's friends). I would recommend adding a `GET /api/users` route.
- [ ] We will not ask that you implement account deletion, so you can remove `DELETE /api/users` for now.
- [ ] It would seem sensible to use `GET /api/posts` to fetch all posts related to a single user - both their own posts and their friends' posts. This would also allow you to eliminate the `GET /api/users/:user_id/posts` route. There shouldn't be a need to fetch singular posts, so you may also remove `GET /api/posts/:post_id`.
- [ ] Let's talk about photo/album routes again when the time comes.

**FRONTEND ROUTES**
- [ ] Please complete this design document.

**Comment by bhanu-gupta** [comment]
Hi Andrew,

Thanks again for your comments. I have resolved all the issues in the schema, mvp and sample state.

For backend routes:
- I added /api/users/:user_id/posts so that I can get the posts of my friend when I visit the profile page of my friend. Will that not be required?
- I have added GET /api/users for getting current users friends but will I not need GET /api/users/:user_id as well to get friends of my friend when I visit the profile page of my friend?

**Comment by andrewlangston** [comment]
Hi Bhanu,

+ `GET /api/users/:user_id/posts` may not be required, depending upon how you choose to fetch posts within your application. If, for example, some high-level component fetches all posts relevant to the current user (their own posts, and all of their friends' posts), then this route will not be necessary. Given that a user timeline demands this sort of fetch anyway, I think we can do without `GET /api/users/:user_id/posts`. Let's make sure to revisit this and discuss before you actually begin implementing posts.
+ Whether or not you need a separate backend route for fetching friends of friends will depend upon the content of the controller action which handles this information. When you fetch users, will you serve up only a user's friends? Or their friends + friends of friends? I leave the decision up to you, noting that if you opt for the former, you will definitely need a `GET /api/users/:user_id` route.

Let me know if you have any questions!

**Comment by bhanu-gupta** [comment]
Thanks Andrew. I have currently removed these two routes. We can see if they are required when I implement the posts. 

Let me know if there is any other feedback.

**Comment by andrewlangston** [comment]
Thanks Bhanu - I am closing this issue.
